name: Java 21 Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Set Up Machine
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Run Static Code Analysis(CheckStyle)
        run: mvn checkstyle:check

      - name: Run Test
        run: mvn test

      - name: Package Application
        run: mvn package -DskipTests

      - name: Upload Generated Artifact
        uses: actions/upload-artifact@v4
        with:
          name: custom-app-artifact-v${{ github.run_number }}
          path: target/*.jar

  deploy-jar:
    needs:
      - build-test
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Set Up Machine
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
          server-id: github

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: custom-app-artifact-v${{ github.run_number }}
          path: target/

      - name: Update Version
        run: mvn versions:set -DnewVersion=1.0.${{ github.run_number }}-SNAPSHOT

      - name: Deploy jar to GitHub Packages
        run: mvn deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}